kind: pipeline
type: docker
name: Build docker image to github

steps:
- name: docker push
  image: plugins/docker
  settings:
    registry: ghcr.io
    repo: ghcr.io/Milesfeng/drone-test
    auto_tag: true
    auto_tag_suffix: linux-amd64
    username: Milesfeng
    password: 
      from_secret: docker_token

trigger:
  branch: 
    - build_docker_image