kind: pipeline
name: run ci

steps:
- name: run unit-test
  image: python
  commands:
  - echo "ok" 

- name: ssh commands
  image: appleboy/drone-ssh
  settings:
    host: 
      from_secret: host 
    username: 
      from_secret: user 
    password: 
      from_secret: password 
    port: 22
    script:
      - cd /home/hsipl/feng/drone
      # - git clone https://github.com/Milesfeng/drone-test.git

- name: slack
  image: plugins/slack
  settings:
    webhook:
      from_secret: slack_webhook
    channel: dev