kind: pipeline
name: run ci

steps:
- name: run pytest
  image: python
  commands:
  - pip install pytest
  - pytest
  - echo "ok" 

- name: ssh commands
  image: appleboy/drone-ssh
  settings:
    host: [ host ]
    username: [ user ]
    password: [ password ]
    port: 22
    script:
      - ls /